# Generated by Django 5.2.3 on 2025-07-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_customer_order_sales'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='demouser',
            table='DemoUser',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='sales',
            table='sales',
        ),
    ]
